pull_request_rules:
  - name: Automatic merge on approval and modified file is index.js
    conditions:
      - "#approved-reviews-by>=0"
      - files = index.js
    actions:
      merge:
        method: merge