pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
    actions:
      merge:
        method: merge
  - name: Automatic merge when file modified is index.js
    conditions:
        - files = index.js
    actions:
      merge:
        method: merge